//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum pjmedia_vid_dev_std_index {
  PJMEDIA_VID_DEFAULT_CAPTURE_DEV = -1,
  PJMEDIA_VID_DEFAULT_RENDER_DEV = -2,
  PJMEDIA_VID_INVALID_DEV = -3
}
