//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum pjsua_stun_use {
  PJSUA_STUN_USE_DEFAULT,
  PJSUA_STUN_USE_DISABLED,
  PJSUA_STUN_RETRY_ON_FAILURE
}
